name: "Publish"

on:
  release:
    types: [published]
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        required: false
        type: string

env:
  ARCHITECTURES: '["amd64", "aarch64"]'
  ADDON_NAME: ha-addon-ghostfolio

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Get version
        id: version
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          elif [ -n "${{ github.event.release.tag_name }}" ]; then
            echo "version=$(echo ${{ github.event.release.tag_name }} | sed s/v//)" >> $GITHUB_OUTPUT
          else
            echo "version=$(curl --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" --silent https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest | jq -r .tag_name | sed s/v// )" >> $GITHUB_OUTPUT
          fi

      - name: Get build matrix
        id: matrix
        uses: home-assistant/builder/actions/prepare-multi-arch-matrix@2026.03.2
        with:
          architectures: ${{ env.ARCHITECTURES }}

  build:
    name: Build add-on
    needs: init
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push add-on
        uses: home-assistant/builder/actions/build-image@2026.03.2
        with:
          arch: ${{ matrix.arch }}
          image: ghcr.io/${{ github.repository_owner }}/${{ env.ADDON_NAME }}-${{ matrix.arch }}
          version: ${{ needs.init.outputs.version }}
          image-tags: |
            ${{ needs.init.outputs.version }}
            latest
          push: true
          container-registry-username: ${{ github.repository_owner }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish multi-arch manifest
    needs: [init, build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Publish multi-arch manifest
        uses: home-assistant/builder/actions/publish-multi-arch-manifest@2026.03.2
        with:
          architectures: ${{ env.ARCHITECTURES }}
          image-name: ${{ env.ADDON_NAME }}
          image-tags: |
            ${{ needs.init.outputs.version }}
            latest
          container-registry-username: ${{ github.repository_owner }}
          container-registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry-prefix: ghcr.io/${{ github.repository_owner }}
